version: '3.9'
services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=defaultuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres